version: '3'
services:
  cronguard_web:
    image: 'andreaswendlandt/cronguard_webserver:latest'
    ports:
      - "8080:80"
    links:
      - cronguard_db
    
  cronguard_db:
    image: 'andreaswendlandt/cronguard_database:latest'
    
  cronguard_daemon:
    image: 'andreaswendlandt/cronguard_daemon:latest'
    links:
      - cronguard_db
    volumes:
      - ../daemon/log/:/var/log
