version: '3'
services:
  cronguard-web:
    image: 'andreaswendlandt/cronguard-web:latest'
    ports:
      - "8080:80"
    links:
      - cronguard-db
    
  cronguard-db:
    image: 'andreaswendlandt/cronguard-db:latest'
    
  cronguard-daemon:
    image: 'andreaswendlandt/cronguard-daemon:latest'
    links:
      - cronguard-db
    volumes:
      - ../daemon/log/:/var/log
