# wordpress
version: '3.5'
services:
  wordpress:
    image: wordpress:apache
    restart: always
    ports:
      - 8084:80
    volumes:
      - ./web_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wordpress_db_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_user_password
    secrets:
      - mysql_user_password

  mariadb:
    image: mariadb:10
    restart: always
    secrets:
      - mysql_root_password
      - mysql_user_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_db_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password

volumes:
  web_data:
secrets:
  mysql_root_password:
    file: ./mysql_root_password.txt
  mysql_user_password:
    file: ./mysql_user_password.txt
