# checkmk
version: '2.4'
services:
  checkmk:
    image: checkmk/check-mk-raw:2.1.0-latest
    privileged: true
    user: root
    restart: always
    ports:
      - 8082:5000
      - 8000:8000
    container_name: mymonitoring
    volumes:
      - monitoring:/omd/sites
      - /etc/localtime:/etc/localtime:ro
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
volumes:
  monitoring:
